var tableauQuestion = [
    {   question : "To shoot safely you must know:",
        propositionA : "Your target",
        propositionB : "What is beyond the target",
        propositionC : "Your target's surroundings",
        propositionD : "All of the above",
        reponse : "D"},

    {   question : "What is not a part of a cartridge or a shotgun shell?",
        propositionA : "Choke",
        propositionB : "Wad",
        propositionC : "Bullet",
        propositionD : "Slug",
        reponse : "A"},

    {   question : "What is a Choke?",
        propositionA : "A valve to warm up your gun",
        propositionB : "The taper in front of a shotgun chamber",
        propositionC : "The taper at the end of a shotgun muzzle",
        propositionD : "None of the above",
        reponse : "C"},

  {   question : "The first cartridge loaded into a magazine presses against the?",
        propositionA : "Magazine Plug",
        propositionB : "Follower",
        propositionC : "Leader",
        propositionD : "Magazine Spring",
        reponse : "B"},

  {   question : "Are smokeless powder and black powder easily substitutable?",
        propositionA : "Yes",
        propositionB : "No",
        propositionC : "Maybe?",
        propositionD : "What's smokeless powder?",
        reponse : "A"},

  {   question : "Your trigger finger must be kept off the trigger until you are actually ready to shoot:",
        propositionA : "Yes",
        propositionB : "No",
        propositionC : "What's a trigger?",
        propositionD : "But the fast pew pew action!",
        reponse : "A"},

  {   question : "Under the Firearms Act, all licence applicants are required to provide a genuine reason for the use or possession of a firearm",
        propositionA : "Yes",
        propositionB : "No",
        propositionC : "Maybe?",
        propositionD : "I do what I want!",
        reponse : "A"},

  {   question : "To load a handgun, you need to push the charged magazine into the grip:",
        propositionA : "Softly and slowly",
        propositionB : "Gently and fast",
        propositionC : "Rudely till you hear the click",
        propositionD : "None of the above",
        reponse : "C"},

  {   question : "Ignorance and carelessness are major causes of firearm accidents",
        propositionA : "Yes",
        propositionB : "No",
        propositionC : "Maybe?",
        propositionD : "I don't understand the question",
        reponse : "A"},

  {   question : "Who can call a cease-fire?",
        propositionA : "Shooters",
        propositionB : "Police",
        propositionC : "Anyone",
        propositionD : "By-standers",
        reponse : "C"},
]
